# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev
version: '3'
vars:
  MAIN: cmd/main.go
  BIN_DIR: ~/.sh/bin
  EXECUTABLE: tm
tasks:
  default:
    cmds:
      - go run {{.MAIN}}
    silent: true
  build:
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -ldflags="-s -w" -o {{.EXECUTABLE}} {{.MAIN}}
      - mv {{.EXECUTABLE}} {{.BIN_DIR}}
    silent: true
  lint:
    cmds:
      - golangci-lint run ./...
    silent: true
  start:
    cmds:
      - go run {{.MAIN}} start
    silent: true
  detach:
    cmds:
      - go run {{.MAIN}} dev
    silent: true
  editor:
    cmds:
      - go run {{.MAIN}} editor
    silent: true
  opencode:
    cmds:
      - go run {{.MAIN}} opencode
    silent: true
  quads:
    cmds:
      - go run {{.MAIN}} quads
    silent: true
  git:
    cmds:
      - go run {{.MAIN}} git
    silent: true
  kill-all:
    cmds:
      - go run {{.MAIN}} kill --all
    silent: true
